version: '2.1'

services:
  openldap:
    container_name: ldap
    build: ./
    environment:
      SLAPD_PASSWORD: grafana
      SLAPD_DOMAIN: grafana.org
      SLAPD_ADDITIONAL_MODULES: memberof
    ports:
      - "389:389"
    networks:
      - grafana-bridgenet

networks:
  grafana-bridgenet:
    driver: bridge

